expansion:
  uspto:
    - /home/freeway/devs/repositories/python/aizynthfinder/aiz_models/uspto_model.onnx
    - /home/freeway/devs/repositories/python/aizynthfinder/aiz_models/uspto_templates.csv.gz
  ringbreaker:
    - /home/freeway/devs/repositories/python/aizynthfinder/aiz_models/uspto_ringbreaker_model.onnx
    - /home/freeway/devs/repositories/python/aizynthfinder/aiz_models/uspto_ringbreaker_templates.csv.gz
filter:
  uspto: /home/freeway/devs/repositories/python/aizynthfinder/aiz_models/uspto_filter_model.onnx
stock:
  zinc: /home/freeway/devs/repositories/python/aizynthfinder/aiz_models/zinc_stock.hdf5