expansion:
  uspto:
    - aiz_models/uspto_model.onnx
    - aiz_models/uspto_templates.csv.gz
  ringbreaker:
    - aiz_models/uspto_ringbreaker_model.onnx
    - aiz_models/uspto_ringbreaker_templates.csv.gz
filter:
  uspto: aiz_models/uspto_filter_model.onnx
stock:
  zinc: aiz_models/zinc_stock.hdf5